baseURL: "https://girishluckhun.com"
languageCode: en-us
title: cd ~
theme: PaperMod

params:
  env: production
  title: Girish Luckhun
  keywords: [Blog]
  author: Girish Luckhun
  DateFormat: "October 2, 2022"
  defaultTheme: auto
  ShowShareButtons: false
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  profileMode:
    enabled: true
    title: Girish Luckhun
    subtitle: Technophile | Linux Enthusiast | Introvert | and other nerd stuff
    imageUrl: img/profile.jpg
    imageWidth: 160
    imageHeight: 160
    imageTitle: Girish Luckhun
    buttons:
      - name: Latest Posts
        url: posts
      - name: Tags
        url: tags
  socialIcons:
    # - name: github
    #   url: https://github.com/patrickeasters
    - name: twitter
      url: https://twitter.com/sudo_gluck
    - name: linkedin
      url: https://www.linkedin.com/in/girish-luckhun-7a19bb184/
    - name: github
      url: https://github.com/RitLuck
    - name: email
      url: mailto:r.luckhun@yahoo.com


menu:
  main:
  - identifier: Whoami
    name: whoami
    url: /whoami/
    weight: 20
  - identifier: tags
    name: ~/tags
    url: /tags/
    weight: 30
  - identifier: posts
    name: ~/posts
    url: /posts/
    weight: 30
  - identifier: search
    name: ~/search
    url: /search/
    weight: 30

outputs:
  home: ["HTML", "RSS", "JSON"]

redirects:
  from "/posts/tech/11-25-2022/"
  to "/posts/11-25-2022/index.md"